### ISSUE TITLE
Device count

### ISSUE THREAD

**Issue by Tvinn-zz** [JonneDatanen/homeassistant-pythemo#1]
I have 13 thermostats installed but it seems the integration is only ever showing 10 of them.

**Comment by JonneDatanen** [comment]
Apparently the api returns only first 10 by default. But it can be changed fortunately. I will edit this when I touch the codebase next time

**Comment by JonneDatanen** [comment]
@Tvinn-zz: I think I fixed it. Please update the integration, and try to add again

**Comment by Tvinn-zz** [comment]
Yes indeed you did, awesome! Now all devices are found. 
Also, great job with the integration, been looking for something like this for a while and discovered it today.
